# Default values for banking-compliance-app
replicaCount: 2

image:
  repository: my-streamlit-app
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 8501
  targetPort: 8501

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: banking-compliance.cloudapp.azure.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: banking-compliance-tls
      hosts:
        - banking-compliance.cloudapp.azure.com

resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Environment variables for the application
env:
  - name: STREAMLIT_SERVER_PORT
    value: "8501"
  - name: STREAMLIT_SERVER_ADDRESS
    value: "0.0.0.0"
  - name: STREAMLIT_SERVER_HEADLESS
    value: "true"

# Database connection secrets
secrets:
  enabled: true
  name: banking-db-secrets
  data:
    AZURE_SQL_SERVER: "agent123.database.windows.net"
    AZURE_SQL_DATABASE: "compliance.db"
    AZURE_SQL_USERNAME: "CloudSA44c529e3"
    AZURE_SQL_PASSWORD: "agent@1995"

# Health checks
healthCheck:
  enabled: true
  path: /_stcore/health
  port: 8501
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

# Pod disruption budget
podDisruptionBudget:
  enabled: true
  minAvailable: 1