GROQ_API_KEY = "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"
APP_USERNAME = "admin"
APP_PASSWORD = "pass123"
DB_SERVER_NAME = "agentdb123.database.windows.net"
DB_NAME = "compliance_db"
DB_USERNAME = "CloudSA98cc6266" # Your full Entra ID UPN
DB_PASSWORD = "agent@123"
DB_PORT = 1433