GROQ_API_KEY = "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"
APP_USERNAME = "admin"
APP_PASSWORD = "pass123"
DB_SERVER_NAME = "agent123.database.windows.net"
DB_NAME = "compliance_db"
DB_USERNAME = "CloudSA44c529e3" # Your full Entra ID UPN
DB_PASSWORD = "agent@1995"
DB_PORT = 1433