GROQ_API_KEY = "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"
APP_USERNAME = "admin"
APP_PASSWORD = "admin_password"
DB_SERVER_NAME = "agentdb123.database.windows.net"
DB_NAME = "compliance_db"
DB_USERNAME = "CloudSA98cc6266" # Your full Entra ID UPN
DB_PASSWORD = "agent@123"
DB_PORT = 1433