GROQ_API_KEY = "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"
APP_USERNAME = "admin"
APP_PASSWORD = "admin_password"
DB_SERVER_NAME = "agentdb123.database.windows.net"
DB_NAME = "compliance_db"
DB_USERNAME = "bankapp_user" # Your full Entra ID UPN
DB_PASSWORD = "SecurePassword123!"
DB_PORT = 1433
