 GROQ_API_KEY = "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"
APP_USERNAME = "admin"
APP_PASSWORD = "admin_password"
DB_SERVER_NAME = "agent123.database.windows.net"
DB_NAME = "compliance_db"
DB_USERNAME = "CloudSA44c529e3" # Your full Entra ID UPN
DB_PASSWORD = "agent@1995"
DB_PORT = 1433
